title: Ina Iontcheva # your name (or website title) here
logo: "/images/IMG_9864.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3+ years of Content Creation and Marketing experience with attention to improving the user experience through blogging, video tutorials, podcasts, and knowledge base articles.
  <br><br>
  Currently at Scalefocus serving as a Content Specialist. I work with Sales, Design and Delivery to produce customer-centric content that drives engagement and generates leads.
  <br><br>
  <a href="https://www.linkedin.com/in/ina-iontcheva">View My LinkedIn Profile</a> 
  <br><br>

  
theme: jekyll-theme-minimal
