title: Ina Iontcheva # your name (or website title) here
logo: "/images/IMG_9864.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an analytical Content Specialist with high communicative competence and a passion for technology.
  <br><br>
  <a href="https://www.linkedin.com/in/ina-iontcheva">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

