title: Ina Iontcheva # your name (or website title) here
logo: "/images/IMG_9864.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3+ years of Content Creation and Marketing experience with attention to improving the user experience through blogging, video tutorials, podcasts, and knowledge base articles.
  <br><br>


  
theme: jekyll-theme-minimal
